/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * ImagePanel.java
 *
 * Created on 2009/12/13, 19:38:12
 */
package autoconverter.view;

import ij.IJ;
import ij.ImagePlus;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Scrollable;

/**
 *
 * @author yfujita
 */
public class ImagePanel extends javax.swing.JPanel {

	private ImagePlus imp;
	private Image img;
	private Point start;
	private Point end;
	private boolean dragF;
	private Rectangle rect;
	private int left_top_x;
	private int left_top_y;
	private int height;
	private int width;

	/**
	 * 最後に選択した左上のx座標
	 * @return
	 */
	public int getLeftTopX(){
		return left_top_x;
	}

	/**
	 * 最後に選択した左上のy座標
	 * @return
	 */
	public int getLeftTopY(){
		return left_top_y;
	}

	/**
	 * 最後に選択した四角の高さ
	 * @return
	 */
	public int getRoiHeight(){
		return height;
	}

	/**
	 * 最後に選択した四角の幅
	 * @return
	 */
	public int getRoiWidth(){
		return width;
	}

	/**
	 * Creates new form ImagePanel
	 */
	public ImagePanel() {
		initComponents();
		start = new Point();
		end = new Point();
		dragF = false;
		rect = new Rectangle();
		left_top_x = 0;
		left_top_y = 0;
		height = 0;
		width = 0;
	}

	@Override
	public void paintComponent(Graphics g) {
		super.paintComponent(g);
		if (imp != null) {
			g.drawImage(imp.getImage(), 0, 0, this);
		}
		if(rect.width > 0 && rect.height > 0){
			g.setColor(Color.YELLOW);
			g.drawRect(rect.x, rect.y, rect.width, rect.height);
		}
	}

	/**
	 * 囲まれた領域があるかどうかを返す.
	 * @return 
	 */
	public boolean isSelected(){
		if(width != 0 && height != 0 ){
			return true;
		} else {
			return false;
		}
	}

	public void setStart(int x, int y) {
		start.setLocation(x, y);
		this.setDragged(true);
	}

	public void setNow(int x, int y) {
		if (start.x > x) {
			left_top_x = x;
			width = start.x - x;
		} else {
			left_top_x = start.x;
			width = x - start.x;
		}
		if (start.y > y) {
			left_top_y = y;
			height = start.y - y;
		} else {
			left_top_y = start.y;
			height = y - start.y;
		}
		rect.setBounds(left_top_x, left_top_y, width, height);
		repaint();
	}

	public void setEnd(int x, int y) {
		end.setLocation(x, y);
		this.setDragged(false);
		if (start.getX() == end.getX() || start.getY() == end.getY()) {
			left_top_x = 0;
			left_top_y = 0;
			height = 0;
			width = 0;
			rect.setBounds(left_top_x, left_top_y, width, height);
		}
		repaint();

	}

	/**
	 * 選択領域を初期化.
	 */
	public void clear(){
		left_top_x = 0;
		left_top_y = 0;
		height = 0;
		width = 0;
		rect.setBounds(left_top_x, left_top_y, width, height);
		repaint();
	}

	public void setDragged(boolean drag) {
		dragF = drag;
	}

	public boolean isDragged() {
		return dragF;
	}


	/**
	 * 画像をセットする.
	 *
	 * @param _imp
	 */
	public synchronized void setImp(ImagePlus _imp) {
		imp = _imp;
		this.setPreferredSize(new Dimension(imp.getWidth(), imp.getHeight()));
		//this.invalidate();
		this.validate();

		//img.getWidth();
		//ImageIcon icon = new ImageIcon(imp.getImage());
		//this.add(new JLabel(icon), BorderLayout.CENTER);
		this.repaint();
	}

	public ImagePlus getImp(){
		return imp;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                setLayout(new java.awt.BorderLayout());
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables
}
